In [1]:
import pandas as pd
from nsepy import get_history
from datetime import date
import datetime as dt

In [2]:
company_name = 'RELIANCE'

In [3]:
 data = get_history(symbol=company_name, start=date(2021,5,1), end=date(2021,6,16))
# df.to_csv('temp.csv')

In [4]:
# data = pd.read_csv('temp.csv', parse_dates=["Date"], index_col="Date")
#data = pd.read_csv('temp.csv', parse_dates=["Date"])

In [5]:
drop_col = ['Symbol', 'Series', 'Trades', 'Turnover']

In [6]:
#data.drop(drop_col, axis='columns', inplace=True)

In [7]:
data['Open Diff']=data['Open']-data['Prev Close']

In [8]:
data['Day Close Diff']=data['Close']-data['Open']

In [17]:
#data['Day Of Week'] = data['Date'].dt.day_name()

In [18]:
data['%Deliverble'] = data['%Deliverble']  * 100

In [19]:
data.head()

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Open Diff,Day Close Diff
Date,,,,,,,,,,,,,,,,
2021-05-03,RELIANCE,EQ,1994.50,1966.00,1979.00,1943.10,1956.0,1959.05,1958.46,10909942,2.136664e+15,343806,3800598,3484.0,-28.50,-6.95
2021-05-04,RELIANCE,EQ,1959.05,1950.00,1967.80,1911.00,1918.0,1916.60,1935.83,10083693,1.952033e+15,325798,4435071,4398.0,-9.05,-33.40
2021-05-05,RELIANCE,EQ,1916.60,1923.35,1938.50,1908.05,1921.5,1920.10,1923.26,5719649,1.100036e+15,190990,1762417,3081.0,6.75,-3.25
2021-05-06,RELIANCE,EQ,1920.10,1921.85,1935.00,1906.60,1932.0,1931.00,1920.95,6749281,1.296502e+15,221666,2830835,4194.0,1.75,9.15
2021-05-07,RELIANCE,EQ,1931.00,1937.75,1955.65,1926.00,1926.8,1931.75,1940.01,5671163,1.100213e+15,188670,2418447,4264.0,6.75,-6.00

In [21]:
# data.reset_index(inplace = True)
#data.set_index('Date', inplace=True)

In [22]:
data.head()

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Open Diff,Day Close Diff
Date,,,,,,,,,,,,,,,,
2021-05-03,RELIANCE,EQ,1994.50,1966.00,1979.00,1943.10,1956.0,1959.05,1958.46,10909942,2.136664e+15,343806,3800598,3484.0,-28.50,-6.95
2021-05-04,RELIANCE,EQ,1959.05,1950.00,1967.80,1911.00,1918.0,1916.60,1935.83,10083693,1.952033e+15,325798,4435071,4398.0,-9.05,-33.40
2021-05-05,RELIANCE,EQ,1916.60,1923.35,1938.50,1908.05,1921.5,1920.10,1923.26,5719649,1.100036e+15,190990,1762417,3081.0,6.75,-3.25
2021-05-06,RELIANCE,EQ,1920.10,1921.85,1935.00,1906.60,1932.0,1931.00,1920.95,6749281,1.296502e+15,221666,2830835,4194.0,1.75,9.15
2021-05-07,RELIANCE,EQ,1931.00,1937.75,1955.65,1926.00,1926.8,1931.75,1940.01,5671163,1.100213e+15,188670,2418447,4264.0,6.75,-6.00

In [14]:
data.tail(45)

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Open Diff,Day Close Diff
Date,,,,,,,,,,,,,,,,
2021-05-03,RELIANCE,EQ,1994.50,1966.00,1979.00,1943.10,1956.00,1959.05,1958.46,10909942,2.136664e+15,343806,3800598,34.84,-28.50,-6.95
2021-05-04,RELIANCE,EQ,1959.05,1950.00,1967.80,1911.00,1918.00,1916.60,1935.83,10083693,1.952033e+15,325798,4435071,43.98,-9.05,-33.40
2021-05-05,RELIANCE,EQ,1916.60,1923.35,1938.50,1908.05,1921.50,1920.10,1923.26,5719649,1.100036e+15,190990,1762417,30.81,6.75,-3.25
2021-05-06,RELIANCE,EQ,1920.10,1921.85,1935.00,1906.60,1932.00,1931.00,1920.95,6749281,1.296502e+15,221666,2830835,41.94,1.75,9.15
2021-05-07,RELIANCE,EQ,1931.00,1937.75,1955.65,1926.00,1926.80,1931.75,1940.01,5671163,1.100213e+15,188670,2418447,42.64,6.75,-6.00
2021-05-10,RELIANCE,EQ,1931.75,1939.00,1946.80,1920.95,1927.10,1926.20,1932.02,6433879,1.243036e+15,197986,2996697,46.58,7.25,-12.80
2021-05-11,RELIANCE,EQ,1926.20,1915.00,1938.55,1910.00,1933.90,1933.15,1929.40,6220217,1.200129e+15,175976,3035544,48.80,-11.20,18.15
2021-05-12,RELIANCE,EQ,1933.15,1930.10,1932.90,1907.00,1913.05,1913.15,1915.34,6081627,1.164838e+15,212378,2760797,45.40,-3.05,-16.95
2021-05-14,RELIANCE,EQ,1913.15,1928.05,1942.00,1906.00,1937.00,1937.30,1925.20,6134079,1.180931e+15,227142,2202511,35.91,14.90,9.25
2021-05-17,RELIANCE,EQ,1937.30,1937.30,1963.45,1930.40,1958.85,1960.35,1950.25,5479424,1.068627e+15,164252,2006899,36.63,0.00,23.05
2021-05-18,RELIANCE,EQ,1960.35,1981.00,2002.60,1972.50,1986.00,1987.95,1987.92,5567958,1.106868e+15,184906,1952871,35.07,20.65,6.95
2021-05-19,RELIANCE,EQ,1987.95,1980.00,2016.45,1972.00,1993.00,1997.05,1998.55,7530294,1.504968e+15,198257,2310132,30.68,-7.95,17.05
2021-05-20,RELIANCE,EQ,1997.05,1997.90,2010.90,1981.00,1982.00,1985.40,1991.75,5271497,1.049953e+15,158144,2175806,41.27,0.85,-12.50
2021-05-21,RELIANCE,EQ,1985.40,1992.00,2009.60,1986.00,1999.60,2002.55,1999.87,4977555,9.954442e+14,182141,1909912,38.37,6.60,10.55
2021-05-24,RELIANCE,EQ,2002.55,2008.00,2009.80,1982.00,1985.05,1985.65,1994.09,3946636,7.869937e+14,130059,1599399,40.53,5.45,-22.35
2021-05-25,RELIANCE,EQ,1985.65,1996.40,1997.00,1960.00,1964.00,1963.15,1974.34,6821015,1.346698e+15,208558,4040447,59.24,10.75,-33.25
2021-05-26,RELIANCE,EQ,1963.15,1975.00,1979.50,1965.30,1967.00,1970.05,1972.33,3452113,6.808701e+14,118469,1452399,42.07,11.85,-4.95
2021-05-27,RELIANCE,EQ,1970.05,1970.30,1993.00,1962.25,1990.00,1976.10,1977.57,12377100,2.447659e+15,219255,7857043,63.48,0.25,5.80
2021-05-28,RELIANCE,EQ,1976.10,1990.00,2105.00,1990.00,2094.45,2094.80,2067.42,26060864,5.387879e+15,642384,7383808,28.33,13.90,104.80
2021-05-31,RELIANCE,EQ,2094.80,2102.00,2191.70,2085.05,2153.50,2160.30,2154.29,27285782,5.878142e+15,624166,7125331,26.11,7.20,58.30
2021-06-01,RELIANCE,EQ,2160.30,2166.00,2202.00,2146.50,2164.30,2168.90,2176.52,12928379,2.813889e+15,390299,3398513,26.29,5.70,2.90
2021-06-02,RELIANCE,EQ,2168.90,2157.00,2209.50,2157.00,2207.00,2201.25,2178.64,11366816,2.476419e+15,258490,5460571,48.04,-11.90,44.25
2021-06-03,RELIANCE,EQ,2201.25,2221.00,2250.00,2196.10,2208.00,2209.65,2221.49,11064116,2.457888e+15,341728,3241763,29.30,19.75,-11.35
2021-06-04,RELIANCE,EQ,2209.65,2214.80,2216.45,2184.25,2186.90,2190.50,2197.67,6677278,1.467447e+15,219435,2770956,41.50,5.15,-24.30
2021-06-07,RELIANCE,EQ,2190.50,2202.00,2242.00,2185.00,2225.05,2227.40,2214.78,7539326,1.669796e+15,227808,2439654,32.36,11.50,25.40
2021-06-08,RELIANCE,EQ,2227.40,2226.60,2227.15,2198.15,2211.50,2214.60,2213.34,4464889,9.882332e+14,147771,1548468,34.68,-0.80,-12.00
2021-06-09,RELIANCE,EQ,2214.60,2219.00,2221.00,2157.95,2178.00,2175.00,2189.57,5265326,1.152880e+15,167739,1817182,34.51,4.40,-44.00
2021-06-10,RELIANCE,EQ,2175.00,2193.40,2230.00,2177.55,2184.80,2183.00,2199.39,6532832,1.436827e+15,215752,1927662,29.51,18.40,-10.40
2021-06-11,RELIANCE,EQ,2183.00,2182.90,2228.00,2180.10,2215.80,2213.15,2214.24,6351520,1.406382e+15,226319,1955394,30.79,-0.10,30.25
2021-06-14,RELIANCE,EQ,2213.15,2215.00,2258.25,2195.05,2245.00,2244.90,2232.14,9383416,2.094510e+15,284426,2698433,28.76,1.85,29.90
2021-06-15,RELIANCE,EQ,2244.90,2261.00,2274.90,2240.30,2244.00,2250.00,2257.44,7002898,1.580861e+15,215805,2501188,35.72,16.10,-11.00
2021-06-16,RELIANCE,EQ,2250.00,2244.90,2247.05,2205.85,2209.55,2211.60,2223.78,4982975,1.108105e+15,163887,1901607,38.16,-5.10,-33.30

In [15]:
# data.dtypes
# data.shape
# data.index

In [16]:
data = data[['Day Of Week','Prev Close','Open', 'High', 'Low', 'Last', 'Close','Open Diff', 'Day Close Diff']]

KeyError: "['Day Of Week'] not in index"

In [57]:
data.head()

,Day Of Week,Prev Close,Open,High,Low,Last,Close,Open Diff,Day Close Diff
Date,,,,,,,,,
2002-04-26,Friday,31.0,40.00,40.00,35.00,37.30,37.40,9.00,-2.60
2002-04-29,Monday,37.4,38.50,39.10,37.65,39.10,38.60,1.10,0.10
2002-04-30,Tuesday,38.6,39.00,40.35,38.50,40.15,40.10,0.40,1.10
2002-05-02,Thursday,40.1,40.25,46.10,40.25,45.10,44.80,0.15,4.55
2002-05-03,Friday,44.8,45.80,47.45,44.55,46.95,46.45,1.00,0.65

In [58]:
# df['Close'].mean()
data_2010 = data.loc['2010']
data_2011 = data.loc['2011']
data_2012 = data.loc['2012']
data_2013 = data.loc['2013']
data_2014 = data.loc['2014']
data_2015 = data.loc['2015']
data_2016 = data.loc['2016']
data_2017 = data.loc['2017']
data_2018 = data.loc['2018']
data_2019 = data.loc['2019']
data_2020 = data.loc['2020']
data_2021 = data.loc['2021']

In [59]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter(company_name+'.xlsx', engine='xlsxwriter')

In [60]:
# Write each dataframe to a different worksheet.
data_2010.to_excel(writer, sheet_name='2010')
data_2011.to_excel(writer, sheet_name='2011')
data_2012.to_excel(writer, sheet_name='2012')
data_2013.to_excel(writer, sheet_name='2013')
data_2014.to_excel(writer, sheet_name='2014')
data_2015.to_excel(writer, sheet_name='2015')
data_2016.to_excel(writer, sheet_name='2016')
data_2017.to_excel(writer, sheet_name='2017')
data_2018.to_excel(writer, sheet_name='2018')
data_2019.to_excel(writer, sheet_name='2019')
data_2020.to_excel(writer, sheet_name='2020')
data_2021.to_excel(writer, sheet_name='2021')

In [61]:
# Close the Pandas Excel writer and output the Excel file.
writer.save()

In [17]:
nifty = get_history(symbol="NIFTY", start=date(2015,1,1), end=date(2015,1,10),index=True)

In [18]:
nifty

               Open     High      Low    Close     Volume      Turnover
Date
2015-01-01  8272.80  8294.70  8248.75  8284.00   56560411  2.321880e+10
2015-01-02  8288.70  8410.60  8288.70  8395.45  101887024  4.715720e+10
2015-01-05  8407.95  8445.60  8363.90  8378.40  118160545  5.525520e+10
2015-01-06  8325.30  8327.85  8111.35  8127.35  172799618  8.089190e+10
2015-01-07  8118.65  8151.20  8065.45  8102.10  164075424  7.464330e+10
2015-01-08  8191.40  8243.50  8167.30  8234.60  143802802  8.147400e+10
2015-01-09  8285.45  8303.30  8190.80  8284.50  152612528  9.305950e+10