In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from nsepy import get_history
plt.style.use('fivethirtyeight')

In [2]:
nifty_50_company_list = ['ADANIPORTS', 'ASIANPAINT', 'AXISBANK','BPCL', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE','BHARTIARTL', 'CIPLA', 'COALINDIA', 'DRREDDY', 'EICHERMOT', 'GAIL', 
                         'GRASIM', 'HCLTECH', 'HDFCBANK', 'HEROMOTOCO', 'HINDALCO', 'HINDPETRO', 'HINDUNILVR', 'HDFC', 'ITC', 'ICICIBANK', 'IBULHSGFIN', 'IOC', 'INDUSINDBK', 'INFY', 
                         'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBIN', 'SUNPHARMA', 'TCS', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 
                         'TITAN', 'UPL', 'ULTRACEMCO', 'VEDL', 'WIPRO', 'YESBANK', 'ZEEL', 'ASHOKLEY']

In [3]:
result_cols = ['Company_Name','Total_Trade','Positive_Trade','Positive_Trade_%','Negative_Trade','Negative_Trade_%']
result_new_dataframe = pd.DataFrame(columns = result_cols)
print(result_new_dataframe)

Empty DataFrame
Columns: [Company_Name, Total_Trade, Positive_Trade, Positive_Trade_%, Negative_Trade, Negative_Trade_%]
Index: []

In [4]:
data = []
total_trade_data = []
no_of_positive_data = []
no_of_negative_data = []
positive_percentage = []
negative_percentage = []
result_data = []

In [5]:
for index, company_name in enumerate(nifty_50_company_list):
    
    data.append('data_'+str(index+1))
    total_trade_data.append('total_trade_data_'+str(index+1))
    no_of_positive_data.append('no_of_positive_data_'+str(index+1))
    no_of_negative_data.append('no_of_negative_data_'+str(index+1))
    positive_percentage.append('positive_percentage_'+str(index+1))
    negative_percentage.append('negative_percentage_'+str(index+1))
    result_data.append('result_data_'+str(index+1))

    start = datetime(2020, 1, 1)
    end = datetime(2021, 12, 3)

    data[index] = get_history(symbol=company_name, start=start, end=end)
    total_trade_data[index] = len(data[index])
    
    data[index]['Day Result'] = (data[index]['Close']- data[index]['Open']).round(decimals = 2)
    
    no_of_positive_data[index] = data[index].loc[(data[index]["Day Result"] > 0)]
    no_of_negative_data[index] = data[index].loc[(data[index]["Day Result"] < 0)]
    
    positive_percentage[index] = (len(no_of_positive_data[index]) * 100) / total_trade_data[index]
    negative_percentage[index] = (len(no_of_negative_data[index]) * 100) / total_trade_data[index]
    
    result_data[index] = {'Company_Name': company_name,
         'Total_Trade': total_trade_data[index],
         'Positive_Trade': len(no_of_positive_data[index]),
         'Positive_Trade_%': positive_percentage[index],
         'Negative_Trade': len(no_of_negative_data[index]),
         'Negative_Trade_%': negative_percentage[index]
        }
    result_new_dataframe = result_new_dataframe.append(result_data[index], ignore_index=True)
    
    print(index+1, company_name, positive_percentage[index], '(+)', negative_percentage[index], '(-)')

1 ADANIPORTS 44.791666666666664 (+) 55.208333333333336 (-)
2 ASIANPAINT 43.541666666666664 (+) 56.458333333333336 (-)
3 AXISBANK 47.083333333333336 (+) 52.916666666666664 (-)
4 BPCL 40.208333333333336 (+) 59.583333333333336 (-)
5 BAJAJ-AUTO 46.25 (+) 53.541666666666664 (-)
6 BAJAJFINSV 46.041666666666664 (+) 53.958333333333336 (-)
7 BAJFINANCE 48.333333333333336 (+) 51.666666666666664 (-)
8 BHARTIARTL 41.041666666666664 (+) 58.75 (-)
9 CIPLA 41.25 (+) 58.541666666666664 (-)
10 COALINDIA 40.625 (+) 58.333333333333336 (-)
11 DRREDDY 43.125 (+) 56.875 (-)
12 EICHERMOT 47.083333333333336 (+) 52.916666666666664 (-)
13 GAIL 40.833333333333336 (+) 58.541666666666664 (-)
14 GRASIM 49.375 (+) 50.208333333333336 (-)
15 HCLTECH 48.541666666666664 (+) 51.458333333333336 (-)
16 HDFCBANK 46.666666666666664 (+) 53.333333333333336 (-)
17 HEROMOTOCO 41.875 (+) 57.916666666666664 (-)
18 HINDALCO 46.666666666666664 (+) 52.708333333333336 (-)
19 HINDPETRO 43.333333333333336 (+) 56.458333333333336 (-)
20 HINDUNILVR 43.125 (+) 56.666666666666664 (-)
21 HDFC 44.791666666666664 (+) 55.208333333333336 (-)
22 ITC 39.583333333333336 (+) 59.791666666666664 (-)
23 ICICIBANK 48.125 (+) 51.666666666666664 (-)
24 IBULHSGFIN 41.041666666666664 (+) 58.541666666666664 (-)
25 IOC 40.208333333333336 (+) 58.333333333333336 (-)
26 INDUSINDBK 42.5 (+) 57.083333333333336 (-)
27 INFY 50.833333333333336 (+) 49.166666666666664 (-)
28 JSWSTEEL 51.041666666666664 (+) 48.541666666666664 (-)
29 KOTAKBANK 44.583333333333336 (+) 55.0 (-)
30 LT 43.333333333333336 (+) 56.666666666666664 (-)
31 M&M 46.458333333333336 (+) 52.916666666666664 (-)
32 MARUTI 42.083333333333336 (+) 57.916666666666664 (-)
33 NTPC 40.208333333333336 (+) 58.75 (-)
34 ONGC 43.333333333333336 (+) 55.833333333333336 (-)
35 POWERGRID 46.041666666666664 (+) 53.541666666666664 (-)
36 RELIANCE 43.541666666666664 (+) 56.458333333333336 (-)
37 SBIN 45.833333333333336 (+) 53.958333333333336 (-)
38 SUNPHARMA 45.416666666666664 (+) 54.583333333333336 (-)
39 TCS 45.625 (+) 53.75 (-)
40 TATAMOTORS 45.208333333333336 (+) 54.583333333333336 (-)
41 TATASTEEL 48.541666666666664 (+) 50.833333333333336 (-)
42 TECHM 52.5 (+) 47.083333333333336 (-)
43 TITAN 43.958333333333336 (+) 55.833333333333336 (-)
44 UPL 46.666666666666664 (+) 53.333333333333336 (-)
45 ULTRACEMCO 46.875 (+) 53.125 (-)
46 VEDL 51.041666666666664 (+) 48.125 (-)
47 WIPRO 46.875 (+) 53.125 (-)
48 YESBANK 29.166666666666668 (+) 60.416666666666664 (-)
49 ZEEL 44.375 (+) 55.625 (-)
50 ASHOKLEY 45.416666666666664 (+) 53.125 (-)

In [6]:
# print(data[1])
# print(total_trade_data[1])
# print(no_of_positive_data[1])
# print(no_of_negative_data[1])
# print(positive_percentage[1])
# print(negative_percentage[1])
# print(result_data[1])

In [7]:
# print(result_new_dataframe)

In [8]:
result_new_dataframe.to_csv('tmp3.csv')

In [9]:
df = pd.read_csv('tmp3.csv')

In [10]:
drop_columns = ['Unnamed: 0']
df.drop(drop_columns, axis=1,inplace = True)

In [11]:
df.head(50)

,Company_Name,Total_Trade,Positive_Trade,Positive_Trade_%,Negative_Trade,Negative_Trade_%
0,ADANIPORTS,480,215,44.791667,265,55.208333
1,ASIANPAINT,480,209,43.541667,271,56.458333
2,AXISBANK,480,226,47.083333,254,52.916667
3,BPCL,480,193,40.208333,286,59.583333
4,BAJAJ-AUTO,480,222,46.250000,257,53.541667
5,BAJAJFINSV,480,221,46.041667,259,53.958333
6,BAJFINANCE,480,232,48.333333,248,51.666667
7,BHARTIARTL,480,197,41.041667,282,58.750000
8,CIPLA,480,198,41.250000,281,58.541667
9,COALINDIA,480,195,40.625000,280,58.333333
10,DRREDDY,480,207,43.125000,273,56.875000
11,EICHERMOT,480,226,47.083333,254,52.916667
12,GAIL,480,196,40.833333,281,58.541667
13,GRASIM,480,237,49.375000,241,50.208333
14,HCLTECH,480,233,48.541667,247,51.458333
15,HDFCBANK,480,224,46.666667,256,53.333333
16,HEROMOTOCO,480,201,41.875000,278,57.916667
17,HINDALCO,480,224,46.666667,253,52.708333
18,HINDPETRO,480,208,43.333333,271,56.458333
19,HINDUNILVR,480,207,43.125000,272,56.666667
20,HDFC,480,215,44.791667,265,55.208333
21,ITC,480,190,39.583333,287,59.791667
22,ICICIBANK,480,231,48.125000,248,51.666667
23,IBULHSGFIN,480,197,41.041667,281,58.541667
24,IOC,480,193,40.208333,280,58.333333
25,INDUSINDBK,480,204,42.500000,274,57.083333
26,INFY,480,244,50.833333,236,49.166667
27,JSWSTEEL,480,245,51.041667,233,48.541667
28,KOTAKBANK,480,214,44.583333,264,55.000000
29,LT,480,208,43.333333,272,56.666667
30,M&M,480,223,46.458333,254,52.916667
31,MARUTI,480,202,42.083333,278,57.916667
32,NTPC,480,193,40.208333,282,58.750000
33,ONGC,480,208,43.333333,268,55.833333
34,POWERGRID,480,221,46.041667,257,53.541667
35,RELIANCE,480,209,43.541667,271,56.458333
36,SBIN,480,220,45.833333,259,53.958333
37,SUNPHARMA,480,218,45.416667,262,54.583333
38,TCS,480,219,45.625000,258,53.750000
39,TATAMOTORS,480,217,45.208333,262,54.583333
40,TATASTEEL,480,233,48.541667,244,50.833333
41,TECHM,480,252,52.500000,226,47.083333
42,TITAN,480,211,43.958333,268,55.833333
43,UPL,480,224,46.666667,256,53.333333
44,ULTRACEMCO,480,225,46.875000,255,53.125000
45,VEDL,480,245,51.041667,231,48.125000
46,WIPRO,480,225,46.875000,255,53.125000
47,YESBANK,480,140,29.166667,290,60.416667
48,ZEEL,480,213,44.375000,267,55.625000
49,ASHOKLEY,480,218,45.416667,255,53.125000